### ISSUE TITLE
failing to create a demo inside front-end toolkits

### ISSUE THREAD

**Issue by sturobson** [springernature/frontend-package-manager#85]
Whilst trying to run the `npm run demo` command in the front-end toolkits repo to create a index.html for global-forms … I've suddenly hitting on an issue … 

the cli error is 

```bash
> frontend-toolkits@ demo /Users/sr/Sites/Clients/Springer/frontend-toolkits
> sn-package-demo "-p" "global-forms]"

  Error: ENOENT: no such file or directory, stat '/Users/sr/Sites/Clients/Springer/frontend-toolkits/to  olkits/packages/packages'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend-toolkits@ demo: `sn-package-demo "-p" "global-forms]"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend-toolkits@ demo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sr/.npm/_logs/2022-09-08T13_40_38_175Z-debug.log
```

and the log is

```bash
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/sr/.nvm/versions/node/v14.20.0/bin/node',
1 verbose cli   '/Users/sr/.nvm/versions/node/v14.20.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'demo',
1 verbose cli   '--',
1 verbose cli   '-p',
1 verbose cli   'global-forms]'
1 verbose cli ]
2 info using npm@6.14.17
3 info using node@v14.20.0
4 verbose run-script [ 'predemo', 'demo', 'postdemo' ]
5 info lifecycle frontend-toolkits@~predemo: frontend-toolkits@
6 info lifecycle frontend-toolkits@~demo: frontend-toolkits@
7 verbose lifecycle frontend-toolkits@~demo: unsafe-perm in lifecycle true
8 verbose lifecycle frontend-toolkits@~demo: PATH: /Users/sr/.nvm/versions/node/v14.20.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/sr/Sites/Clients/Springer/frontend-toolkits/node_modules/.bin:/opt/homebrew/bin:/Users/sr/.nvm/versions/node/v14.20.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle frontend-toolkits@~demo: CWD: /Users/sr/Sites/Clients/Springer/frontend-toolkits
10 silly lifecycle frontend-toolkits@~demo: Args: [ '-c', 'sn-package-demo "-p" "global-forms]"' ]
11 silly lifecycle frontend-toolkits@~demo: Returned: code: 1  signal: null
12 info lifecycle frontend-toolkits@~demo: Failed to exec demo script
13 verbose stack Error: frontend-toolkits@ demo: `sn-package-demo "-p" "global-forms]"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/sr/.nvm/versions/node/v14.20.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/Users/sr/.nvm/versions/node/v14.20.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1088:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
14 verbose pkgid frontend-toolkits@
15 verbose cwd /Users/sr/Sites/Clients/Springer/frontend-toolkits
16 verbose Darwin 21.6.0
17 verbose argv "/Users/sr/.nvm/versions/node/v14.20.0/bin/node" "/Users/sr/.nvm/versions/node/v14.20.0/bin/npm" "run" "demo" "--" "-p" "global-forms]"
18 verbose node v14.20.0
19 verbose npm  v6.14.17
20 error code ELIFECYCLE
21 error errno 1
22 error frontend-toolkits@ demo: `sn-package-demo "-p" "global-forms]"`
22 error Exit status 1
23 error Failed at the frontend-toolkits@ demo script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by sturobson** [comment]
things I've tried 

- `rimraf node_modules`
- changing the node version to 15.0.0 and latest
- running the command for different components
- trying this in several different branches

**Comment by sturobson** [comment]
As @alexkilgour pointed out I had a rogue `]` in my command so ran it correctly - it failed with this output 

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/sr/.nvm/versions/node/v14.20.0/bin/node',
1 verbose cli   '/Users/sr/.nvm/versions/node/v14.20.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'demo',
1 verbose cli   '--',
1 verbose cli   '-p',
1 verbose cli   'global-forms'
1 verbose cli ]
2 info using npm@6.14.17
3 info using node@v14.20.0
4 verbose run-script [ 'predemo', 'demo', 'postdemo' ]
5 info lifecycle frontend-toolkits@~predemo: frontend-toolkits@
6 info lifecycle frontend-toolkits@~demo: frontend-toolkits@
7 verbose lifecycle frontend-toolkits@~demo: unsafe-perm in lifecycle true
8 verbose lifecycle frontend-toolkits@~demo: PATH: /Users/sr/.nvm/versions/node/v14.20.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/sr/Sites/Clients/Springer/frontend-toolkits/node_modules/.bin:/opt/homebrew/bin:/Users/sr/.nvm/versions/node/v14.20.0/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle frontend-toolkits@~demo: CWD: /Users/sr/Sites/Clients/Springer/frontend-toolkits
10 silly lifecycle frontend-toolkits@~demo: Args: [ '-c', 'sn-package-demo "-p" "global-forms"' ]
11 silly lifecycle frontend-toolkits@~demo: Returned: code: 1  signal: null
12 info lifecycle frontend-toolkits@~demo: Failed to exec demo script
13 verbose stack Error: frontend-toolkits@ demo: `sn-package-demo "-p" "global-forms"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/sr/.nvm/versions/node/v14.20.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/Users/sr/.nvm/versions/node/v14.20.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1088:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
14 verbose pkgid frontend-toolkits@
15 verbose cwd /Users/sr/Sites/Clients/Springer/frontend-toolkits
16 verbose Darwin 21.6.0
17 verbose argv "/Users/sr/.nvm/versions/node/v14.20.0/bin/node" "/Users/sr/.nvm/versions/node/v14.20.0/bin/npm" "run" "demo" "--" "-p" "global-forms"
18 verbose node v14.20.0
19 verbose npm  v6.14.17
20 error code ELIFECYCLE
21 error errno 1
22 error frontend-toolkits@ demo: `sn-package-demo "-p" "global-forms"`
22 error Exit status 1
23 error Failed at the frontend-toolkits@ demo script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by sturobson** [comment]
a 'quick fix' for design tokens in turn made Travis unhappy with everything … [this fix in toolkits](https://github.com/springernature/frontend-toolkits/pull/806) fixed it
